### ISSUE TITLE
Create an application icon (РУТлид)

### ISSUE THREAD

**Issue by Xandr070** [ImmortalIdiot/RUTLead-project-activity#20]

**Comment by Xandr070** [comment]
![image](https://github.com/ImmortalIdiot/RUTLead-project-activity/assets/129608390/dc6f17a2-783c-4dff-95f6-1be6906152e2)

**Comment by ImmortalIdiot** [comment]
Should the image have a background?

**Comment by ImmortalIdiot** [comment]
Nice job, man
