### ISSUE TITLE
Design the list of students

### ISSUE THREAD

**Issue by NN171** [ImmortalIdiot/RUTLead-project-activity#8]

**Comment by Xandr070** [comment]
![image](https://github.com/ImmortalIdiot/RUTLead-project-activity/assets/129608390/ad99ca57-9ab5-44a2-b6a9-88c5f7a69054)

**Comment by Xandr070** [comment]
![image](https://github.com/ImmortalIdiot/RUTLead-project-activity/assets/129608390/f9887e5e-c94d-4c98-a468-aaad2f5dbb16)

**Comment by Xandr070** [comment]
Done

**Comment by ImmortalIdiot** [comment]
It looks cool. Well done
